// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmshaduyqukvcdomsfsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtc2hhZHV5cXVrdmNkb21zZnN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNDg2MjIsImV4cCI6MjA2OTgyNDYyMn0.qbEK87HpDiji182dkiHjCzROptdO1WTO6SAxICzoXds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});